name: Django CI

on:
  push:
    branches: [ "akash-master" ]
  pull_request:
    branches: [ "akash-master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        
        
    - name: Merge code to production
      run: |
          git config user.name "akashvats29"
          git config user.email "<vatsakash168@gmail.com>"
          git checkout master
          git merge --no-ff ${{ github.sha }} -m "Merge pull request #${{ github.event.pull_request.number }}"
